# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
#   bundle exec jekyll serve --livereload
#
#
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bioinformatics Journal Club
email: noemail@noemail.orgß
description: >- # this means to ignore newlines until "baseurl:"
  Bioinformatics Journal Club
#baseurl: "/test-url" # the subpath of your site, e.g. /blog
baseurl: "/bioinformatics_journal_club"
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
#remote_theme: just-the-docs/just-the-docs
#theme: minima
plugins:
# - jekyll-feed

# collections
collections:
  resources:
#  speakers:

# updates
paginate: 5
paginate_path: "/news/page:num"

# FORMATTING
#
#fixed_navbar: top
defaults:
  -
    scope:
      path: ""
    values:
      hero_height: is-small
      #hero_image: /dceg_workshops_template/assets/grey_background.png
      hero_darken: false
  -
    scope:
      path: meetings
    values:
      hero_height: is-small
      show_menubar: true
      menubar: sessions_sidebar
  -
    scope:
      type: posts
    values:
      hero_height: is-small
      show_sidebar: true
  -
    scope:
      path: meetings/23-05-10
    values:
      title: "23-05-10: Using Population Descriptors in Genetics and Genomics Research"
      parent: meetings
      nav_order: 1
      tabs: meeting1_tabs
  -
    scope:
      path: meetings/23-08-09
    values:
      title: "23-08-09: Large Language Models (LLMs) like GPT-4 and AI agents"
      parent: meetings
      nav_order: 2
      tabs: meeting2_tabs

  -
    scope:
      path: meetings/23-09-27
    values:
      title: "23-09-27: Gene Set Summarization using Large Language Models"
      parent: meetings
      nav_order: 2
      tabs: meeting3_tabs    

  -
    scope:
      path: meetings/24-02-21
    values:
      title: "24-02-21: The Helicobacter pylori Genome Project: insights into H. pylori population structure from analysis of a worldwide collection of complete genomes"
      parent: meetings
      nav_order: 2
      tabs: meeting4_tabs      

  -
    scope:
      path: meetings/24-03-13
    values:
      title: "24-03-13: Transcriptomic profiling of lung adenocarcinoma from never-smokers reveals molecular subtypes with clinical implications"
      parent: meetings
      nav_order: 2
      tabs: meeting5_tabs       

  -
    scope:
      path: meetings/24-04-10
    values:
      title: "24-04-10: Large-scale snRNA-seq dataset revealed cell subtype-specific effects of genetic variation in the Alzheimer’s disease brain"
      parent: meetings
      nav_order: 2
      tabs: meeting6_tabs    

  -
    scope:
      path: meetings/24-05-08
    values:
      title: "24-05-08: Establishing a single-cell eQTL dataset of lung tissues from Asian women never-smokers to elucidate cell-type specific genetic regulation"
      parent: meetings
      nav_order: 2
      tabs: meeting7_tabs       

  -
    scope:
      path: meetings/24-06-12
    values:
      title: "24-06-12: A new method of adjusting for correlated dose errors, or where there may be substantial curvature in dose response, and comparison with other methods of dose error correction"
      parent: meetings
      nav_order: 2
      tabs: meeting8_tabs    

  -
    scope:
      path: meetings/24-09-11
    values:
      title: "24-09-11: F-MAGMA: leveraging epigenomic data for enhanced target gene identification in GWAS"
      parent: meetings
      nav_order: 2
      tabs: meeting9_tabs  

  -
    scope:
      path: meetings/24-10-09
    values:
      title: "24-10-09: CPRD: Real-world Data Source for Epidemiologic Research"
      parent: meetings
      nav_order: 2
      tabs: meeting10_tabs  

  -
    scope:
      path: meetings/24-11-13
    values:
      title: "24-11-13: Building FAIR Bioinformatics Workflows: A Case Study Using De Novo Mutations Variant Calling in Snakemake"
      parent: meetings
      nav_order: 2
      tabs: meeting11_tabs       

  -
    scope:
      path: meetings/25-01-08
    values:
      title: "25-01-08: The Geisinger DiscovEHR cohort: 233,185 people with exome sequencing and longitudinal EHR data"
      parent: meetings
      nav_order: 2
      tabs: meeting12_tabs  

  -
    scope:
      path: meetings/25-02-12
    values:
      title: "25-02-12: Utilizing Commercial Real-World Data: Truveta"
      parent: meetings
      nav_order: 2
      tabs: meeting13_tabs    

  -
    scope:
      path: meetings/25-03-12
    values:
      title: "25-03-12: Caris Precision Oncology Alliance™ (POA) and CODEai™ clinico-genomics research database overview and demonstration"
      parent: meetings
      nav_order: 2
      tabs: meeting14_tabs   

  -
    scope:
      path: meetings/25-04-09
    values:
      title: "25-04-09: Towards a FAIRer Real World Data Commons: real-time processing of individual level patient discharge reports collected by NY's SPARCS program"
      parent: meetings
      nav_order: 2
      tabs: meeting15_tabs   

  -
    scope:
      path: meetings/25-05-14
    values:
      title: "25-05-14: The Department of Defense Serum Repository and Other Military Research Infrastructure"
      parent: meetings
      nav_order: 2
      tabs: meeting16_tabs        

  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
